export const ICON_ALTS: Record<number, string> = {
  1: "Flask",
  2: "Football",
  3: "Flask",
  4: "Sun",
  5: "Hand spock",
  6: "Bug",
  7: "Moon",
  8: "Snowflake",
  9: "Turkish lira sign",
  10: "Car",
  11: "Home",
  12: "Cloud",
  13: "Bell",
  14: "Camera",
  15: "Truck",
  16: "Face smile",
  17: "Star",
  18: "Headphone",
};
