import type { Metadata } from "next";
import { Atkinson_Hyperlegible } from "next/font/google";
import "./globals.css";

const atkinson = Atkinson_Hyperlegible({
  weight: "700",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Memory Game",
  description: "Generated by Frontend Mentor",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${atkinson.className} antialiased text-300 sm:text-450 text-blue-muted bg-gray-lighter`}
      >
        {children}
      </body>
    </html>
  );
}
